CREATE TABLE HEARTBEAT (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	VENDING_ID VARCHAR(255) NOT NULL,
	LAST_PING_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	NEED_UPDATE_CONFIG TINYINT(1) DEFAULT 0
);
CREATE UNIQUE INDEX HEARTBEAT_VENDING_ID ON HEARTBEAT (VENDING_ID);